server.port=8080
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Routing and path rewrite for customer-service
spring.cloud.gateway.routes[0].id=customer-route
spring.cloud.gateway.routes[0].uri=lb://customer-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/customer/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/customer/(?<segment>.*), /customers/$\{segment}

# Routing and path rewrite for billing-service
spring.cloud.gateway.routes[1].id=billing-route
spring.cloud.gateway.routes[1].uri=lb://billing-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/billing/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/billing/(?<segment>.*), /billings/$\{segment}
