server.port=8087
spring.application.name=payment-service

# Resilience4j Circuit Breaker Settings
resilience4j.circuitbreaker.instances.paymentService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=5000
resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true
